#auto: true
markdown: rdiscount

# pygments: true

#markdown: kramdown
#kramdown:
#  input: GFM

# pygments: true
highlighter: true

permalink: /blog/:year/:month/:day/:title

# 分页大小
paginate: 10
# 最新文章显示数
last_pages: 10

title: Leeyee's Blog
url: http://leeyee.github.io
author: leeyee

#GitHub项目地址
github: https://github.com/oxcow/

#分析
analytics:
  provider: test
  google: 
    tracking_id: 'UA-40641589-1'

#评论
comments:
  provider: disqus
  uyan:
    uid: 1785947
  disqus:
    short_name: oxcow

#分享
shares:
  provider: jiathis
  jiathis:
    uid: 1354586152725188

#_plugins/sitemap_generator.rb https://github.com/kinnetica/jekyll-plugins
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

#_plugins/rssgenerator.rb https://github.com/agelber/jekyll-rss
rss_name: "feed.xml"