markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
  hard_wrap:  true
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
      coderay_wrap:              div
      coderay_line_numbers:      inline
      coderay_line_number_start: 1
      coderay_tab_width:         4
      coderay_bold_every:        10
      coderay_css:               style

permalink: /blog/:year/:month/:day/:title/

# 分页大小
paginate: 10
# 最新文章显示数
last_pages: 10

name: Leeyee's Blog
description: 我的技术类博客
url: http://iyiguo.net
author: leeyee

#GitHub项目地址
github: https://github.com/oxcow/

#分析
analytics:
  provider: google,baidu
  google:
    tracking_id: 'UA-40641589-1'

#评论
comments:
  provider: disqus
  uyan:
    uid: 1785947
  disqus:
    short_name: oxcow

#分享
shares:
  provider: jiathis
  jiathis:
    uid: 1354586152725188

gems:
- jekyll-mentions
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
