markdown: kramdown
#highlighter: rouge

kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
  coderay:
      coderay_wrap:              div
      coderay_line_numbers:      inline
      coderay_line_number_start: 1
      coderay_tab_width:         4
      coderay_bold_every:        10
      coderay_css:               style

permalink: /blog/:year/:month/:day/:title

# 分页大小
paginate: 10
# 最新文章显示数
last_pages: 10

title: Leeyee's Blog
url: http://leeyee.github.io
author: leeyee

#GitHub项目地址
github: https://github.com/oxcow/

#分析
analytics:
  provider:
  google:
    tracking_id: 'UA-40641589-1'

#评论
comments:
  provider:
  uyan:
    uid: 1785947
  disqus:
    short_name: oxcow

#分享
shares:
  provider: jiathis
  jiathis:
    uid: 1354586152725188

#_plugins/sitemap_generator.rb https://github.com/kinnetica/jekyll-plugins
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

#_plugins/rssgenerator.rb https://github.com/agelber/jekyll-rss
rss_name: "feed.xml"