auto: true
markdown: rdiscount
pygments: true

permalink: /blog/:year/:month/:day/:title

paginate: 10

title: Leeyee's Blog
url: http://leeyee.github.com
author: leeyee

       
#GitHub项目地址

github: https://github.com/oxcow/

#分析
analytics:
  provider: google
  google: 
    tracking_id: 'UA-40641589-1'

#评论
comments:
  provider: uyan
  uyan:
    uid: 1785947
  disqus:
    short_name: oxcow

#分享
shares:
  provider: jiathis
  jiathis:
    uid: 1354586152725188
  