auto: true
markdown: rdiscount
pygments: true

permalink: /blog/:year/:month/:day/:title

paginate: 10

title: Leeyee's Blog
url: http://leeyee.github.com
author: leeyee

       


# 分析
analytics:
  provider: google
  google: 
    tracking_id: 'UA-40641589-1'

# 评论
comments:
  provider: disqus
  disqus:
    short_name: oxcow