# Jekyll default config: http://jekyllrb.com/docs/configuration/default/

# Kramdown options: https://kramdown.gettalong.org/options.html
kramdown:
  toc_levels: 1..3
  #syntax_highlighter: rouge # default rouge
  # https://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # 需要配合 rougify style 使用.  rougify help style and rougify style github > assets/css/rouge.github.css
  syntax_highlighter_opts:
    default_lang: java



permalink: /blog/:year/:month/:day/:title/

# 分页大小
paginate: 10
# 最新文章显示数
last_pages: 10

name: Leeyee's Blog
description: 我的技术类博客
url: http://iyiguo.net
author: leeyee

#GitHub项目地址
github: https://github.com/oxcow/

#分析
analytics:
#provider: google,baidu
#google:
#tracking_id: 'UA-40641589-1'

#评论
comments:
#provider: disqus
#disqus:
#short_name: oxcow

plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

profile: true

defaults:
  - scope:
      type: "pages"
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"
sass:
  style: compressed